BEGIN TRANSACTION;

-- Table: bug
CREATE TABLE "bug" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"posted_time"	REAL NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"image"	BLOB,
	PRIMARY KEY("id" AUTOINCREMENT)
);


-- Table: comment
CREATE TABLE "comment" (
	"id"	INTEGER NOT NULL UNIQUE,
	"bug_id"	INTEGER NOT NULL,
	"text"	TEXT NOT NULL,
	"is_solution"	INTEGER NOT NULL DEFAULT 0 CHECK(is_solution IN (0, 1)),
	FOREIGN KEY("bug_id") REFERENCES "bug"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

COMMIT TRANSACTION;
